config/routes.rb
Rails.application.routes.draw do

  get 'home/about'
  get 'comments/create'
devise_for :end_users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'questions#index'
get '/about' => 'home#about'


# end_userのルーティング
resources :end_users do
  resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
end

resources :questions do
  get 'search' => 'questions#search'
  resources :comments, only: [:create, :destroy]
  resources :answers, except: [:index] do
		resource :favorites, only: [:create, :destroy]

	end
end

end

app/models/question.rb
class Question < ApplicationRecord

	belongs_to :end_user
	has_many :answers
	has_many :comments

	# =============== validate =======================================
	validates :title, presence: true, length: {maximum: 200, miximum: 10}
	validates :body, presence: true, length: {maximum: 3000, miximum: 10}
	# ================================================================

	scope :recent, -> { order(created_at: :desc) }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_end_user!, only: [:new, :edit, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  #================================= 検索機能 =========================================
    @q = Question.ransack(params[:q])
    @search_questions = @q.result(distinct: true).page(params[:page]).per(10)
    # ransackをインストールしたのでransackメソッドが使用可。
    # 現場で使える Ruby on Rails 5速習実践ガイド p292, p318
  #================================= 検索機能 =========================================
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answers = @question.answers.all
    @search = Answer.ransack(params[:q])
    @comment = Comment.new
  end


  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.end_user = current_end_user

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:end_user_id, :title, :body)
    end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_comment.html.erb
<h4>コメント一覧</h4>
<% question.comments.each do |comment| %>
  <tr>
    <div class="comment-box clearfix">
      <div class="comment-author clearfix">
        <%= link_to end_user_path(comment.end_user), class: "end_user_#{comment.end_user.id}" do %>
          <%= comment.end_user.name %>
        <% end %>
        <div class="pull-right">
          投稿日時 : <%= comment.created_at.strftime('%Y/%m/%d') %>
        </div>
      </div>
      <% if comment.end_user == current_end_user %>
      <span><%= comment.body %></span><%= link_to '削除',question_comment_path(question, comment),class: 'btn btn-danger pull-right', style: "margin: 0 auto;" , method: :delete, remote: true %>
      <% end %>
    </tr>
  </div>
<% end %>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
<!--     <% if question.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

            <ul>
                <% question.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %> -->


    <div class="col-sm-6 col-sm-offset-3">
        <div class="field">
            <%= form.label :title %>
            <%= form.text_field :title, class: "form-control" %>
            <p>（最大200文字）</p>
        </div>

        <div class="field">
            <%= form.label :質問内容 %>
            <%= form.text_area :body, rows:15, id:"input-text", class: "form-control" %>
            <p id="counter">0文字（最大3000文字）</p>
        </div>

        <div class="actions">
            <%= form.submit class:"btn btn-default" %>
        </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'layouts/error', obj: @question %>
<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <p id="notice"><%= notice %></p>

<!-- ========================= 検索フォーム =============================== -->
            <h1>Questions</h1>
            <%= search_form_for @q, class: 'mb-5' do |f| %>
                <div class="from-group.row">
                    <%= f.label :title_cont, "タイトル", class:'col-sm-2 col-form-label' %>
                </div>
                <div class="col-sm-8">
                    <%= f.search_field :title_cont,  class:'form-control' %>
                </div>
                <div class="form-group col-sm-2">
                    <%= f.submit '検索', class: 'btn btn-primary' %>
                </div>
            <% end %>
<!-- =================================================================== -->

            <table class="table">
                <thead>
                    <tr>
                        <th>質問者</th>
                        <th>タイトル</th>
                        <th>投稿日時</th>
                        <th></th>
                        <th colspan="3"></th>
                    </tr>
                </thead>


                <!-- ================= 検索した時のレビュー ================== -->
                <tbody>
                    <% @search_questions.each do |question| %>
                        <tr>

                                <td style="height: 80px;"><%= question.end_user.name %></td>
                                <td style="width: 50%; word-break: break-word;"><%= question.title %></td>
                                <td><%= question.created_at.strftime('%Y/%m/%d %H:%M') %></td>
                                <td><%= question.answers.count %>個の回答があります。</td>
                                <td><%= link_to 'Show', question, class: "btn btn-default" %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <!-- ======================================================== -->
            <br>
            <div class="clearfix">
                <div class="col-sm-6 col-sm-offset-3">
                    <%= link_to '新しく質問する', new_question_path, class: "btn btn-default btn-block"  %>
                </div>
            </div>

            <!-- ================== ページネーション　================  -->

            <div class="sm-3" style="text-align: center;">
                <p><%= paginate @search_questions %></p>
                <p><%= page_entries_info @search_questions %></p>
            </div>

            <!-- ==================================================  -->

        </div>
    </div>
</div>

app/views/questions/new.html.erb
<h1>質問作成画面</h1>

<%= render 'layouts/error', obj: @question %>
<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path, class: "btn btn-default" %>

app/views/questions/show.html.erb
<div class="container">
  	<div class="row">
  		<h3>質問詳細 & 回答一覧</h3>
  		<p id="notice"><%= notice %></p>
    	<!-- ======================= 質問内容表示部分 ============================ -->
    	<div class="col-xs-6">
    		<p>投稿日時 <%= @question.created_at.strftime('%Y/%m/%d %H:%M') %>
    		<strong>質問者:</strong>
			<%= @question.end_user.name %>
    		<div class="panel panel-info" style="height: 400px; word-break: break-word;">
    			<div class="panel-heading">

					<span>
					  <strong>Title:</strong>
					  <%= @question.title %>
					</span>
				</div>
				<div class="panel-body">
					<p>
					  <strong>質問内容</strong><br>
					  <%= @question.body %>
					</p>
				</div>
			</div>
			<%= link_to '回答する', new_question_answer_path(@question), class: "btn btn-default" %> |
			<% if @question.end_user == current_end_user  %>
				<%= link_to 'Edit', edit_question_path(@question), class: "btn btn-default" %> |
			<% end %>
			<%= link_to 'Back', questions_path, class: "btn btn-default"  %>
    	<!-- ================================================================== -->

    	<!-- ==================== コメント表示部分 =============================== -->

			<div id="comment_index_<%= @question.id %>"><br>
				<%= render partial: 'questions/comment', locals: {question: @question} %>
			</div><br>
			<%= form_with model:[@question, @comment],data: {remote: true} do |f|  %>
				<%= f.text_area :body, rows:'5', class: "form-control",placeholder: "質問に対するコメントをここに書いてください" %>
				<br>
				<%= f.submit "送信する", class: "btn btn-default btn-base-1 mt-20 pull-right" %>
			<% end %>
		</div>

    	<!-- ================================================================== -->

    	<!-- ==================== 回答内容表示部分 =============================== -->
		<div class="col-xs-6">
			<p><%= @question.answers.count %>件の回答があります。<p>
			<% if @question.answers.count != 0 %>

				<% @answers.each do |answer| %>
					<div class="panel panel-info" style="word-break: break-word;">
						<div class="panel-heading" style="margin-bottom: 10px;">
							<strong>回答者</strong>
							<%= answer.end_user.name %>

							<span>
						  		<strong>Title:</strong>
								<%= answer.title %>
							</span>

							<!-- ============ いいね機能 ==================== -->
							<div id="favorites_buttons_<%= answer.id %>">
							<%= render partial: 'favorites/favorite', locals: {question_answers: @question, answer: answer} %>
							</div>
							<!-- ========================================== -->
						</div>

						<div class="panel-body">
							<p>
							  <strong>回答内容</strong><br>
							  <%= raw Rinku.auto_link(simple_format(h(answer.body))) %>
							</p>
							<%= link_to '詳細',question_answer_path(@question, answer),class: "btn btn-default" %>
						</div>
					</div>
				<% end %>
				<% else %>
					<div class="well" style="text-align: center">
						<strong>まだ回答がありません</strong><br>
						<br>
						<%= link_to '回答する', new_question_answer_path(@question), class: "btn btn-default" %>
					</div>
				</div>
			<% end %>
		</div>
    <!-- ====================================================================== -->
	</div>
</div>