config/routes.rb
Rails.application.routes.draw do

  get 'home/about'
  get 'comments/create'
devise_for :end_users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'questions#index'
get '/about' => 'home#about'


# end_userのルーティング
resources :end_users do
  resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
end

resources :questions do
  get 'search' => 'questions#search'
  resources :comments, only: [:create, :destroy]
  resources :answers, except: [:index] do
		resource :favorites, only: [:create, :destroy]

	end
end

end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :end_user
	belongs_to :question
	has_many :favorites

	# =============== validate =================
	validates :title, presence: true, length: {maximum: 200, miximum: 10}
	validates :body ,presence: true, length: {maximum: 3000}

	# ==========================================
    def favorited_by?(end_user)
        favorites.where(end_user_id: end_user.id).exists?
    end

    # =================== favoriteのレコード数をカウント ==================

  	# =================================================================
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [ :edit, :update, :destroy]
  before_action :authenticate_end_user!, only: [:new, :edit, :destroy]

  def index
    @answers = Answer.all
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    @answer.end_user_id = current_end_user.id
    @answer.question_id = @question.id

  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.end_user_id = current_end_user.id
    @answer.question_id = @question.id

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id] )
  end



  def edit
  end

  def update
  end

  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:end_user_id, :title, :body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/destroy.html.erb
<h1>Answers#destroy</h1>
<p>Find me in app/views/answers/destroy.html.erb</p>

app/views/answers/edit.html.erb
<h1>Answers#edit</h1>
<p>Find me in app/views/answers/edit.html.erb</p>

app/views/answers/index.html.erb
<h1>Answers#index</h1>
<p>Find me in app/views/answers/index.html.erb</p>

app/views/answers/new.html.erb
<h1>回答投稿</h1>

<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%= form_for [@question, @answer], url: question_answers_path do |form| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>

  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, rows:15, id:"input-text", class: "form-control"  %>
      <p id="counter">0文字（最大3000文字）</p>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-default" %>
    <%= link_to 'back', question_path(@question), class: "btn btn-default" %>
  </div>
<% end %>

    </div>
  </div>
</div>

app/views/answers/show.html.erb
<div class="container">
  	<div class="row">
  		<h3>回答詳細</h3>
    	<div class="col-xs-6 col-sm-offset-3">

	    		<div class="panel panel-info" style="word-break: break-word;">
	    			<div class="panel-heading">
						<p id="notice"><%= notice %></p>

						<span>
						  <strong>質問者:</strong>
						  <%= @answer.end_user.name %>


						</span>

						<span>
						  <strong>Title:</strong>
						  <%= @answer.title %>

						</span>
					</div>
					<div class="panel-body">
						<p>
						  <strong>回答内容</strong><br>
						  <%= @answer.body %>

						</p>
					</div>
				</div>
					<%= link_to 'Back', :back, class: "btn btn-default"  %>
		</div>
		
	</div>
</div>

app/views/answers/update.html.erb
<h1>Answers#update</h1>
<p>Find me in app/views/answers/update.html.erb</p>