config/routes.rb
Rails.application.routes.draw do

  get 'home/about'
  get 'comments/create'
devise_for :end_users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'questions#index'
get '/about' => 'home#about'


# end_userのルーティング
resources :end_users do
  resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
end

resources :questions do
  get 'search' => 'questions#search'
  resources :comments, only: [:create, :destroy]
  resources :answers, except: [:index] do
		resource :favorites, only: [:create, :destroy]

	end
end

end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
has_many :questions
has_many :answers
has_many :comments
has_many :favorites

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  # =============== validate =======================================
  validates :name, presence: true, length: {maximum: 16, miximum: 2}
  # ================================================================

  def followed_by?(end_user)
    passive_relationships.find_by(following_id: end_user.id).present?
  end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
  before_action :set_end_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_end_user!

  def index
    @end_users = EndUser.all
  end

  def new
  end

  def create
    @end_user = Question.new(question_params)

    respond_to do |format|
      if @end_user.save
        format.html { redirect_to @question, notice: 'End_user was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @questions = @end_user.questions

  end

  def edit
  end

  def update
    respond_to do |format|
      if @end_user.update(end_user_params)
        format.html { redirect_to @end_user, notice: 'End_user was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @end_user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @end_user.destroy
    respond_to do |format|
      format.html { redirect_to end_users_path, notice: 'End_user was successfully destroyed.' }
      format.json { head :no_content }
    end
    flash[:notice] = "end_userを削除しました。"
  end

  def follows
    end_user = EndUser.find(params[:id])
    @end_users = end_user.followings
  end

  def followers
    end_user = EndUser.find(params[:id])
    @end_users = end_user.followers
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_end_user
      @end_user = EndUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def end_user_params
      params.require(:end_user).permit(:name)
    end
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/views/end_users/edit.html.erb
<h2>ユーザー情報編集</h2>
<%= form_with(model: @end_user, local: true) do |form| %>
    <% if @end_user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@end_user.errors.count, "error") %> prohibited this question from being saved:</h2>

            <ul>
                <% @end_user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="clearfix">
        <div class="col-sm-6">
            <div class="field">
                <%= form.label :name  %>
                <%= form.text_field :name, class: "form-control" %>
            </div>

            <div class="field">
                <%= form.label :email %>
                <%= form.text_area :email, class: "form-control" %>
            </div>

            <div class="actions">
                <%= form.submit '保存' %>
            </div>
        </div>
    </div>
<% end %>



<%= link_to 'Show', @end_user, class: "btn btn-default" %> |
<%= link_to 'Back', end_users_path, class: "btn btn-default" %>

app/views/end_users/followers.html.erb
<h2>フォロワー　一覧</h2>
<div class="clearfix">
	<div class="col-sm-8 col-sm-offset-2">

			<div class="well well-sm col-sm-4 pull-right" style="text-align: center;">
			<%= @end_users.count %>人からフォローされています。</div>
		<table class="table">
			<!-- ====================== フォローユーザー一覧  ============== -->
			<thead>
				<tr>
					<th style="width: 600px;">ユーザー名</th>
					<th></th>
				</tr>
			</thead>

			<% @end_users.each do |end_user| %>
				<tbody>
					<tr>
						<td style="height: 50px;"><%= link_to end_user.name, end_user_path(end_user.id) %></td>
						<td>
						    <% if current_end_user != end_user %>
						        <% if end_user.followed_by?(current_end_user) %>
						            <p><%=link_to "フォローを外す", end_user_relationships_path(end_user.id), method: :delete,class: " btn btn-danger" %></p>
						         <% else %>
									<p><%=link_to "フォローする", end_user_relationships_path(end_user.id), method: :post, class: "btn btn-default" %></p>
						        <% end %>
						    <% end %>
						</td>
					</tr>
				</tbody>
			<% end %>
			<!-- ======================================================= -->
		</table>
		<hr>
	</div>
</div>

<div style="text-align: center;">
	<%= link_to 'back', end_users_path, class: "btn btn-default" %>
</div>

app/views/end_users/follows.html.erb
<h2>フォローユーザー一覧</h2>
<div class="clearfix">
	<div class="col-sm-8 col-sm-offset-2">

		<div class="well well-sm col-sm-4 pull-right" style="text-align: center;">
			<%= @end_users.count %>人フォローしています。</div>
		<table class="table">
			<!-- ====================== フォローユーザー一覧  ============== -->
			<thead>
				<tr>
					<th style="width: 600px;">ユーザー名</th>
					<th></th>
				</tr>
			</thead>

			<% @end_users.each do |end_user| %>
				<tbody>
					<tr>
						<td style="height: 50px;"><%= link_to end_user.name, end_user_path(end_user.id) %></td>
						<td>
						    <% if current_end_user != end_user %>
						        <% if end_user.followed_by?(current_end_user) %>
						            <div><%=link_to "フォローを外す", end_user_relationships_path(end_user.id), method: :delete,class: " btn btn-danger" %></div>
						        <% end %>
						    <% end %>
						</td>
					</tr>
				</tbody>
			<% end %>
			<!-- ======================================================= -->
		</table>
		<hr>
	</div>
</div>

<div style="text-align: center;">
	<%= link_to 'back', end_users_path, class: "btn btn-default" %>
</div>

app/views/end_users/index.html.erb
<div class="container">
	<div class="row">
		<h2>ユーザー一覧</h2>

<!-- ======================= フォロー/フォロワーボタン =========================== -->
		<div class="col-sm-5 col-sm-offset-1">
			<span><%=link_to "フォロー", follows_end_user_path(current_end_user.id), class: " btn btn-default btn-block" %></span>
		</div>
		<div class="col-sm-5">
			<span><%=link_to "フォロワー", followers_end_user_path(current_end_user.id), class: "btn btn-default btn-block" %></span>
		</div>
<!-- ======================= フォロー/フォロワーボタン =========================== -->
		<div class="col-sm-10 col-sm-offset-1">
			<table class="table float-lg-right"><br>
				<thead>
			  		<tr>
					    <th>name</th>
					    <th></th>
					    <th></th>
					</tr>
				</thead>
				<tbody>
				<% @end_users.each do |end_user| %>
				    <tr>
					    <td><%= end_user.name %></td>
					    <td><%=link_to "show", end_user_path(end_user.id), class: "btn btn-default " %></td>
					    <td>
							<% if current_end_user != end_user %>
								<% if end_user.followed_by?(current_end_user) %>
									<p><%=link_to "フォロー済み", end_user_relationships_path(end_user.id), method: :delete, class: "btn btn-danger pull-right" %></p>
								<% else %>
									<p><%=link_to "フォローする", end_user_relationships_path(end_user.id), method: :post, class: "btn btn-default pull-right" %></p>
								<% end %>
							<% end %>
							</td>
					    <td><% if current_end_user.admin? %>
					    	<%=link_to "退会させる", end_user_path(end_user), method: :delete, class: "btn btn-danger", data: {confirm: "削除しますか？"} %></td>
					    <% end %>
					</tr>
				 <% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/end_users/show.html.erb
<h1>ユーザー詳細</h1>

<!-- =========== ユーザー基本情報  =============================== -->
<table class="table">
	<thead>
		<tr>
			<th>ユーザー名</th>
			<th>email</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= @end_user.name %></td>
			<td><%= @end_user.email %></td>
						<% if current_end_user.id == @end_user.id %>
				<td><%= link_to 'edit', edit_end_user_path(@end_user), class: "btn btn-default" %> </td>
			<% end %>
			<% if current_end_user.id == @end_user.id %>
				<td><%=link_to "退会する", end_user_path(@end_user), method: :delete, class: "btn btn-danger", data: {confirm: "削除しますか？"} %></td>
			<% elsif current_end_user.admin? %>
				<td><%=link_to "退会させる", end_user_path(@end_user), method: :delete, class: "btn btn-danger", data: {confirm: "削除しますか？"} %></td>
			<% end %>
		</tr>
	</tbody>
</table>
<!-- ========================================================== -->

<!-- ==================== ユーザーが投稿した質問 ====================== -->
<div class="clearfix">
	<div class="col-sm-10 col-sm-offset-1">
	    <table class="table">
	        <thead>
	        	<tr>
		            <th style="text-align: center;">Title</th>
		            <th colspan="3"></th>
		        </tr>
	        </thead>

	        <tbody>
				<% @questions.each do |question| %>
					<tr>
						<td style="width: 600px; word-break: break-word;">
							<%= question.title %>
						</td>
						<td><%= link_to 'Show', question, class: "btn btn-default" %></td>
						<% if current_end_user.nil? %>
							<td></td>
							<td></td>
						<% elsif question.end_user.id == current_end_user.id %>
							<td><%= link_to '削除', question, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
						<% end %>
					</tr>
				<% end %>
	        </tbody>
	      </table>
	</div>
</div>
<!-- ============================================================== -->

<div style="text-align: center">
	<%= link_to 'Back', end_users_path, class: "btn btn-default" %>
</div>