config/routes.rb
Rails.application.routes.draw do

  get 'home/about'
  get 'comments/create'
devise_for :end_users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'questions#index'
get '/about' => 'home#about'


# end_userのルーティング
resources :end_users do
  resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
end

resources :questions do
  get 'search' => 'questions#search'
  resources :comments, only: [:create, :destroy]
  resources :answers, except: [:index] do
		resource :favorites, only: [:create, :destroy]

	end
end

end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :end_user
	belongs_to :question
	has_many :favorites

	# =============== validate =================
	validates :title, presence: true, length: {maximum: 200, miximum: 10}
	validates :body ,presence: true, length: {maximum: 3000}

	# ==========================================
    def favorited_by?(end_user)
        favorites.where(end_user_id: end_user.id).exists?
    end

    # =================== favoriteのレコード数をカウント ==================

  	# =================================================================
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :question
	belongs_to :end_user

	# =============== validate ======================
	# validates :comment, presence: true
	# ===============================================

end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
has_many :questions
has_many :answers
has_many :comments
has_many :favorites

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  # =============== validate =======================================
  validates :name, presence: true, length: {maximum: 16, miximum: 2}
  # ================================================================

  def followed_by?(end_user)
    passive_relationships.find_by(following_id: end_user.id).present?
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :end_user
	belongs_to :answer
end

app/models/question.rb
class Question < ApplicationRecord

	belongs_to :end_user
	has_many :answers
	has_many :comments

	# =============== validate =======================================
	validates :title, presence: true, length: {maximum: 200, miximum: 10}
	validates :body, presence: true, length: {maximum: 3000, miximum: 10}
	# ================================================================

	scope :recent, -> { order(created_at: :desc) }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "EndUser"
    belongs_to :follower, class_name: "EndUser"
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [ :edit, :update, :destroy]
  before_action :authenticate_end_user!, only: [:new, :edit, :destroy]

  def index
    @answers = Answer.all
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    @answer.end_user_id = current_end_user.id
    @answer.question_id = @question.id

  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.end_user_id = current_end_user.id
    @answer.question_id = @question.id

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id] )
  end



  def edit
  end

  def update
  end

  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:end_user_id, :title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@question = Question.find(params[:question_id])
    @comment = current_end_user.comments.new(comment_params)
    @comment.question_id = @question.id
    @comment.save
    # redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:question_id])

    @question_comment = Comment.find(params[:id])
    if @question_comment.end_user != current_end_user
      redirect_to request.referer
    end
    @question_comment.destroy
    
  end

  private
	def comment_params
    params.require(:comment).permit(:end_user_id,:question_id,:body)
	end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
  before_action :set_end_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_end_user!

  def index
    @end_users = EndUser.all
  end

  def new
  end

  def create
    @end_user = Question.new(question_params)

    respond_to do |format|
      if @end_user.save
        format.html { redirect_to @question, notice: 'End_user was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @questions = @end_user.questions

  end

  def edit
  end

  def update
    respond_to do |format|
      if @end_user.update(end_user_params)
        format.html { redirect_to @end_user, notice: 'End_user was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @end_user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @end_user.destroy
    respond_to do |format|
      format.html { redirect_to end_users_path, notice: 'End_user was successfully destroyed.' }
      format.json { head :no_content }
    end
    flash[:notice] = "end_userを削除しました。"
  end

  def follows
    end_user = EndUser.find(params[:id])
    @end_users = end_user.followings
  end

  def followers
    end_user = EndUser.find(params[:id])
    @end_users = end_user.followers
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_end_user
      @end_user = EndUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def end_user_params
      params.require(:end_user).permit(:name)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @answer = Answer.find(params[:answer_id])
    @question_answer_id = params[:question_id]
  	favorite = current_end_user.favorites.build(answer_id: params[:answer_id])
    favorite.save
    # redirect_to request.referer ---非同期処理のためのコメントアウト
  end

  def destroy
    @answer = Answer.find(params[:answer_id])
    @question_answer_id = params[:question_id]
    favorite = Favorite.find_by(answer_id: params[:answer_id], end_user_id: current_end_user.id)
    favorite.destroy
    # redirect_to request.referer ---非同期処理のためのコメントアウト
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger" style="width: 80%; margin: 10px auto;">
      <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

      <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container-fluid">
	<div class="row">
		<div class='col-sm-3 col-sm-offset-9'>
    		<p style="color: #666; display: center; line-height: 90px; ">maruopi portfolio.inc</p>
    	</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maruopi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/0617b3186b.js" crossorigin="anonymous"></script>
  </head>

        <body>
          <!--header-->
          <header>
          <div class="logo">
            <strong>maruopi</strong>
          </div>
          <div class="end-user-header-nav">
            <% if end_user_signed_in? %>
              <span class="social">
                <%= link_to  end_user_path(current_end_user.id) do %>
                  <i class="fas fa-home">Home</i>
                <% end %>
              </span>

              <span class="social">
                <%= link_to  end_users_path  do %>
                  <i class="fas fa-user">User</i>
                <% end %>
              </span>

              <span class="social">
                <%= link_to questions_path do %>
                  <i class="fas fa-book">question</i>
                <% end %>
              </span>

              <span class="social">
                <%= link_to destroy_end_user_session_path, method: :delete, data: {confirm: "ログアウトします。よろしいですか？"} do %>
                  <i class="fas fa-sign-out-alt">Logout</i>
                <% end %>
              </span>

            <% else %>

              <span class="social">
                <%= link_to root_path do %>
                 <i class="fas fa-home">Home</i>
                <% end %>
              </span>

              <span class="social">
                <%= link_to about_path do %>
                 <i class="fas fa-user">About</i>
                <% end %>
              </span>

              <span class="social">
                <%= link_to new_end_user_registration_path do %>
                  <i class="fas fa-user-plus">新規登録</i>
                <% end %>
              </span>

              <span class="social">
                <%= link_to new_end_user_session_path do %>
                  <i class="fas fa-sign-in-alt">ログイン</i>
                <% end %>
              </span>
            <% end %>
          </div>

            </header>

            <div class="container">
              <div class="row">
                <div class="col-xs-12">
                  <%= yield %>
                </div>
              </div>
            </div>
            <footer>
              <%= render 'layouts/footer' %>
            </footer>
        </body>




</html>